services:
#  db:
#    image: postgres:latest
#    container_name: postgresql_db
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - ${POSTGRES_PORT}:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql

#  qdrant:
#    image: qdrant/qdrant
#    container_name: qdrant_vector_db
#    ports:
#      - ${QDRANT_PORT}:6333
#    volumes:
#      - ./qdrant_data:/qdrant/storage
#    environment:
#      QDRANT__SERVICE__GRPC_PORT: 6334

  database:
    image: neo4j:5.11
    ports:
      - ${NEO4J_PORT_BOLT}:7687
      - ${NEO4J_PORT_HTTP}:7474
    volumes:
      - ./data:/data
      - ./neo4j.dump:/var/lib/neo4j/neo4j.dump
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME-neo4j}/${NEO4J_PASSWORD-password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 15s
        timeout: 30s
        retries: 10

  embedding_model:
    image: ghcr.io/clems4ever/torchserve-all-minilm-l6-v2:latest
    ports:
      - 8080:8080

volumes:
  neo4j_data:
##  pgdata:
#  qdrant_data: