from dotenv import load_dotenv
import os

load_dotenv()

STACK_OVERFLOW_CLIENT_ID=os.getenv("CLIENT_ID")
STACK_OVERFLOW_CLIENT_SECRET=os.getenv("CLIENT_SECRET")
STACK_OVERFLOW_API_KEY=os.getenv("STACK_OVERFLOW_API_KEY")

COHERE_KEY=os.getenv("COHERE_KEY")
GEMINI_KEY=os.getenv("GEMINI_KEY")

POSTGRES_USER=os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD=os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST=os.getenv("POSTGRES_HOST")
POSTGRES_PORT=os.getenv("POSTGRES_PORT")
POSTGRES_DB=os.getenv("POSTGRES_DB")

QDRANT_PORT=os.getenv("QDRANT_PORT")
QDRANT_HOST=os.getenv("QDRANT_HOST")
QDRANT_COLLECTION_NAME=os.getenv("QDRANT_COLLECTION_NAME")

VECTOR_SEARCH_THRESHOLD=os.getenv("VECTOR_SEARCH_THRESHOLD")
